#Config of Games | ArkaniaStudios

database:
  host: 'localhost'
  username: 'root'
  password: ''
  schema: 'arkaniastudios'
  port: 3306

scoreboard:
  lines:
    - "Welcome, {NAME}!"
    - "Score: 0"
    - "Health: 100%"